### ISSUE TITLE
Confusion about PacCoin

### ISSUE THREAD

**Issue by peschu123** [wmcorless/paccoin#13]
Hi,

I‘m a bit confused about PacCoin. Why is there paccoin.net and paccoinofficial.com ?? Is it the same? Is it different and why etc...?? 

Thx for clarifying...

BR,

Peter

**Comment by wmcorless** [comment]
Hi Peter, Paccoin.net is associated with Saul Wolf and his group who are
working on Paccoin Cash ($PAC) They are offering a redemption coin offering
RCO for their new coin using Paccoin.

**Comment by peschu123** [comment]
Hi William,
thank you very much for the quick reply! I'm aware of the RCO so far. 

I'm not a developer, but (if I understand right) this means $PAC is a hardfork of PacCoin and both will exist in the end? Or will there be only the new $PAC? Will they be "rivals" or is it more of a consensus decision to work around actual PacCoin "issues"? 

I hope this is not too much off topic for your repo and I hope you can give me some light. ;-)

Thanks a lot for your for efforts

**Comment by wmcorless** [comment]
there is a lot of different information. from what I know the new coin $PAC
is based on DASH, They are spreading false information about paccoin having
issues, so people will give them billions of paccoins so they can make
money off the proof of stake.

**Comment by peschu123** [comment]
thx a lot

**Comment by minimobci** [comment]
William, what you are saying is, that the "investors" will send them all the purchased coins for RCO(which they will keep and not burn) to get 1000:1 for the new $PAC
And they will use the old PAC to do proof of stake and make income?

**Comment by wmcorless** [comment]
there is no such thing as burn. as long as a wallet is on the network the
coins will exist in that wallet. If they choose to not spend it, that is
their decision.

**Comment by nathanielcook** [comment]
From [https://paccoin.net/wp-content/uploads/2018/01/PAC_BRAND_GUIDELINES_REV1.pdf](https://paccoin.net/wp-content/uploads/2018/01/PAC_BRAND_GUIDELINES_REV1.pdf):

> PAC – Who we are?
> PacCoin is alternative digital currency. Originally founded in 2013 by William Corliss as the Pacifica Nation’s official coin. Almost exactly four years later the Crypto community rebranded and relaunched PacCoin. The coin was launched with a new purpose and direction and supportive resources. The coin now stands for the People’s Alternative Choice coin. The PacCoin network of developers has banded together with the community to bring PacCoin back into the top of the Cryptosphere.

Doesn't sound based on DASH...

**Comment by wmcorless** [comment]
different coin

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
